HAVE_CURL := $(shell which curl)

$(info Does system have curl tool?)
$(if $(HAVE_CURL), \
	$(info Yes. curl is here), \
	$(info No. curl is not here.))


.PHONY: all
.DEFAULT: all
all: ; $(info)