NOW = $(shell date)
FILE_COUNT = $(shell ls | wc -l)
FILES = $(shell ls)
CWD = $(shell pwd)

$(info NOW = $(NOW))
$(info FILE_COUNT = $(FILE_COUNT))
$(info FILES = $(FILES))
$(info CWD = $(CWD))

.PHONY: all

all: ; @true