# Take three arguments and make a date with them by inserting slashes between the three arguments
# function make_date(DAY, MONTH, YEAR)
make_date = $1/$2/$3

today := $(call make_date,5,5,2014)

$(info The date is $(today))

.PHONY: all
.DEFAULT: all
all: ;

