TRUE = true
FALSE =
or = $(if $1$2,T)

$(info or)
$(info true,   true: $(call or,TRUE,TRUE))
$(info true,  false: $(call or,TRUE,FALSE))
$(info false,  true: $(call or,FALSE,TRUE))
$(info false,  true: $(call or,FALSE,TRUE))
$(info false, false: $(call or,FALSE,FALSE))