include gmsl
c-value := 0
counter = $(c-value)$(eval c-value := $(call plus,$(c-value),1))

$(info Starts at $(counter))
$(info Then it's $(counter))
$(info And then it's $(counter))

.PHONY: all

all: ; @true